version: '3.8'

services:
  db-decoder-ead-authuser:
    image: postgres:16.3-alpine
    container_name: db-decoder-ead-authuser
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db_authuser
    volumes:
      - db-decoder-ead-authuser:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-decoder-ead-authuser: