server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_authuser
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true